import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { GiHamburgerMenu } from 'react-icons/gi'
import { useState } from 'react'
import { BoltIcon, DevicePhoneMobileIcon, GlobeAltIcon, ScaleIcon } from '@heroicons/react/24/outline'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <section id="home-intro-screen" className='px-4 font-sans min-h-[50rem] text-black'>
        <Hook />
      </section>
      <section id="home-intro-screen" className='px-4 font-sans min-h-[50rem] text-black'>
        <Reviews />
      </section>
      <section className='px-4 font-sans text-black bg-slate-100 flex justify-center'>
        <Example />
      </section>
      <section className='px-4 font-sans text-black bg- flex justify-center'>
        <Example2 />
      </section>
    </>
  )
}

export function Navbar() {
  return (
    <div id="navbar" className='w-full h-10 bg-black p-7 text-white font-sans flex items-center justify-between'>
      <div className='text-2xl font-bold'>Randy</div>
      <div className='flex-auto flex justify-end items-center gap-3'>
        <div className='text-x'><GiHamburgerMenu /></div>
        <div className='text-sm bg-white shadow-md px-3 py-2 rounded-sm text-black'>Start For Free</div>
      </div>
    </div>
  )
}

export function Hook() {
  return (
    <div id="hook-div" className='w-full h-40 px-2 pt-16 flex flex-col gap-16'>
      <div>
        <h6 className="text-[.7rem] tracking-wider pb-2">MEET RANDY</h6>
        <h1 className='text-4xl font-bold'>Create amazing college level essays 10X faster with AI</h1>
      </div>

      <div className='flex flex-col gap-8'>
        <p>Randy is the AI Essay Platform that helps you break through creative blocks to create amazing, original essays 10X faster.</p>
        <button className='w-full bg-black text-white py-3 rounded-md text-md font-bold border-2 border-black'>Start For Free</button>
        <button className='w-full bg-white text-black py-3 rounded-md text-md font-bold border-2 border-black'>Get A Demo</button>
      </div>

    </div>
  )
}

const features = [
  {
    name: 'Near instant essays',
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Maiores impedit perferendis suscipit eaque, iste dolor cupiditate blanditiis ratione.',
    icon: GlobeAltIcon,
  },
  {
    name: 'Up to 1000 words',
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Maiores impedit perferendis suscipit eaque, iste dolor cupiditate blanditiis ratione.',
    icon: ScaleIcon,
  },
  {
    name: 'Citations included',
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Maiores impedit perferendis suscipit eaque, iste dolor cupiditate blanditiis ratione.',
    icon: BoltIcon,
  },
]

export function Example() {
  return (
    <div className="bg-slate-100 py-24 sm:py-32 lg:py-40">
      <div className="mx-auto max-w-7xl px-6 lg:px-8">
        <div className="sm:text-center">
          <p className="mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">A better way to write essays</p>
          <p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-gray-600">
            Our AI-powered writing tool can generate a high-quality essay in a fraction of the time it would take you to do it yourself.
            Simply input your assignment requirements and let the AI handle the rest.
          </p>
        </div>

        <div className="mt-20 max-w-lg sm:mx-auto md:max-w-none">
          <div className="grid grid-cols-1 gap-y-16 md:grid-cols-2 md:gap-x-12 md:gap-y-16">
            {features.map((feature) => (
              <div key={feature.name} className="relative flex flex-col gap-6 sm:flex-row md:flex-col lg:flex-row">
                <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-black text-white sm:shrink-0">
                  <feature.icon className="h-8 w-8" aria-hidden="true" />
                </div>
                <div className="sm:min-w-0 sm:flex-1">
                  <p className="text-lg font-semibold leading-8 text-gray-900">{feature.name}</p>
                  <p className="mt-2 text-base leading-7 text-gray-600">{feature.description}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  )
}

export function Example2() {
  return (
    <div className="bg-white w-full ">
      <div className="mx-auto min-h-[25rem] max-w-7xl py-12 px-4 sm:px-6 lg:flex lg:items-center lg:justify-between lg:py-16 lg:px-8">
        <h2 className="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">
          <span className="block">Ready to dive in?</span>
          <span className="block text-slate-400">Start your free trial today.</span>
        </h2>
        <div className="mt-8 flex lg:mt-0 lg:flex-shrink-0">
          <div className="inline-flex rounded-md shadow">
            <a
              href="#"
              className="inline-flex items-center justify-center rounded-md border border-transparent bg-black px-5 py-3 text-base font-medium text-white hover:bg-slate-700"
            >
              Get started
            </a>
          </div>
          <div className="ml-3 inline-flex rounded-md shadow">
            <a
              href="#"
              className="inline-flex items-center justify-center rounded-md border border-transparent bg-white px-5 py-3 text-base font-medium text-black hover:bg-slate-50"
            >
              Learn more
            </a>
          </div>
        </div>
      </div>
    </div>
  )
}




export function Reviews() {
  return (
    <>
    <div className='border-[1px] h-40 border-slate-100 p-3 shadow-md rounded-md flex items-center gap-2'>
      <div className='bg-slate-400 rounded-md w-[20rem] h-[90%]'></div>
      <div className='flex flex-col gap-2 p-2 items-between'>
        <p className='text-[0.8rem]'>This is a review. I am a college kid addicted to free TikTok dopamine and I got finnessed by this company.</p>
        <div className='text-sm font-bold'>Sarah Silverman, TikToker</div>
      </div>
    </div><div className='border-[1px] h-40 border-slate-100 p-3 shadow-md rounded-md flex items-center gap-2'>
        <div className='bg-slate-400 rounded-md w-[20rem] h-[90%]'></div>
        <div className='flex flex-col gap-2 p-2 items-between'>
          <p className='text-[0.8rem]'>This is a review. I am a college kid addicted to free TikTok dopamine and I got finnessed by this company.</p>
          <div className='text-sm font-bold'>Sarah Silverman, TikToker</div>
        </div>
      </div><div className='border-[1px] h-40 border-slate-100 p-3 shadow-md rounded-md flex items-center gap-2'>
        <div className='bg-slate-400 rounded-md w-[20rem] h-[90%]'></div>
        <div className='flex flex-col gap-2 p-2 items-between'>
          <p className='text-[0.8rem]'>This is a review. I am a college kid addicted to free TikTok dopamine and I got finnessed by this company.</p>
          <div className='text-sm font-bold'>Sarah Silverman, TikToker</div>
        </div>
      </div><div className='border-[1px] h-40 border-slate-100 p-3 shadow-md rounded-md flex items-center gap-2'>
        <div className='bg-slate-400 rounded-md w-[20rem] h-[90%]'></div>
        <div className='flex flex-col gap-2 p-2 items-between'>
          <p className='text-[0.8rem]'>This is a review. I am a college kid addicted to free TikTok dopamine and I got finnessed by this company.</p>
          <div className='text-sm font-bold'>Sarah Silverman, TikToker</div>
        </div>
      </div>
      </>
  )
}